ARG ELK_VERSION=7.10.1

FROM elasticsearch:${ELK_VERSION}
#COPY --chown=elasticsearch:root config/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml
# RUN bin/elasticsearch-plugin install --batch analysis-icu
RUN ls -lah /usr/share/elasticsearch/
